server:
  port: 8081
  servlet:
    context-path: /profiles

spring:
  application:
    name: Profile Service
  config:
    import: optional:secrets.properties
  neo4j:
    uri: bolt://${DB_HOST}:${DB_PORT}
    authentication:
      username: ${DB_USER}
      password: ${DB_PASSWORD}
  premium:
    clock-skew-seconds=0
    start-grace-seconds=0