version: '3.8'
services:
  # RabbitMQ Service với healthcheck
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 30s

  # WebSocket Gateway
  websocket-gateway:
    build:
      context: ./websocket-gateway
      dockerfile: Dockerfile
    image: websocket-gateway:latest
    environment:
      - MassageBrokerConnections__HostName=rabbitmq
      - MassageBrokerConnections__Port=5672
    networks:
      - appnet
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  # Finance Socket Service
  finance-socket:
    build:
      context: ./finance-Socket
      dockerfile: Dockerfile
    image: finance-socket:latest
    ports:
      - "6002:8080"
    environment:
      - MassageBrokerConnections__HostName=rabbitmq
      - MassageBrokerConnections__Port=5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - appnet
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "6001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - websocket-gateway
    networks:
      - appnet

volumes:
  rabbitmq_data:

networks:
  appnet:
    driver: bridge