server:
  port: 8999

app:
  api-prefix: /api/v1

spring:
  application:
    name: API Gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: crawler_service
              uri: http://localhost:5002
              predicates:
                - Path=${app.api-prefix}/crawler/**
              filters:
                - StripPrefix=2
            - id: post_comment_service
              uri: http://localhost:8084
              predicates:
                - Path=${app.api-prefix}/post-comment/**
              filters:
                - StripPrefix=2
            - id: auth_service
              uri: http://localhost:8080
              predicates:
                - Path=${app.api-prefix}/auth/**
              filters:
                - StripPrefix=2
            - id: profile_service
              uri: http://localhost:8081
              predicates:
                - Path=${app.api-prefix}/profiles/**
              filters:
                - StripPrefix=2
            - id: notification_service
              uri: http://localhost:8082
              predicates:
                Path=${app.api-prefix}/notification/**
              filters:
                StripPrefix=2
            - id: payment_service
              uri: http://localhost:8089
              predicates:
                Path=${app.api-prefix}/payment/**
              filters:
                StripPrefix=2
            - id: market_service
              uri: http://localhost:8085
              predicates:
                - Path=${app.api-prefix}/market/**
              filters:
                - StripPrefix=2
            - id: backtest_service
              uri: http://localhost:5005
              predicates:
                - Path=${app.api-prefix}/backtest/**
              filters:
                - StripPrefix=2
            - id: prediction_service
              uri: http://localhost:5006
              predicates:
                - Path=${app.api-prefix}/prediction/**
              filters:
                - StripPrefix=2

