server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: API Gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: notification_service
              uri: http://localhost:8082
              predicates:
                - Path=${app.api-prefix}/notification/**
              filters:
                - StripPrefix=2
            - id: auth_service
              uri: http://localhost:8080
              predicates:
                - Path=${app.api-prefix}/**
              filters:
                - StripPrefix=2
            - id: profile_service
              uri: http://localhost:8081
              predicates:
                - Path=${app.api-prefix}/profile/**
              filters:
                - StripPrefix=2

